name: CI for restaurant

on:
  pull_request:
    branches: [main, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: ci for reGov
        working-directory: ./Backend
        run: |
          npm i
          npm run build
